### ISSUE TITLE
階数移動のための2D/3D地図切り替え

### ISSUE THREAD

**Issue by NaokiTakahashi12** [NaokiTakahashi12/Robot-Service-2020#1]
対象とする移動経路には階層移動を含むため，2D/3Dの地図を切り替える必要がある．

**Comment by taishiyamamoto** [comment]
まだ試作段階ですが2D/3Dマップを切り替えるノードを作りました．
https://github.com/taishiyamamoto/map_changer

**Comment by NaokiTakahashi12** [comment]
以下確認ください．

- [x] 動作確認

- [ ] 2D/3Dマップのファイル設定

- [ ] 切り替え後のロボットの初期位置

**Comment by NaokiTakahashi12** [comment]
動作確認ができていないままだが，そもそもロボットにエレベータを押す機能がなく，人が手助けする必要が発生するためクローズする．
